const MANAGER_CONFIG = {
  HEAT_CHECK_INTERVAL: 8000,
  CULL_THRESHOLD_HOURS: 4,
  STALE_GENOME_HOURS: 24,
  SWARM_SPREAD_PERCENT: 0.005,
};

const LEGION_CONFIG = {
  DREAMER_WORKER_COUNT: 1,
  TOTAL_SHADOW_CAPACITY: 50,
  ACTIVE_ASSET_SWARM_DENSITY: 10,
  ENABLE_DEVELOPER_LOGS: false,
  PASSIVE_ASSET_MONITOR_COUNT: 10,
};

export { MANAGER_CONFIG, LEGION_CONFIG };
