export default [
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        console: 'readonly',
        process: 'readonly',
        global: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        Date: 'readonly',
        Math: 'readonly',
        Promise: 'readonly',
        JSON: 'readonly',
        Object: 'readonly',
        Array: 'readonly',
        String: 'readonly',
        Number: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        parseFloat: 'readonly',
        parseInt: 'readonly',
        isNaN: 'readonly',
        isFinite: 'readonly',
        Buffer: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        fetch: 'readonly',
        WebSocket: 'readonly',
        crypto: 'readonly',
        require: 'readonly',
        module: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        exports: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-undef': 'off',
      'no-console': 'off',
      'no-undef-init': 'off',
      'no-redeclare': 'off',
      'no-constant-condition': 'off',
      'no-fallthrough': 'off',
      'no-unreachable': 'off',
      'no-unused-expressions': 'off',
      'no-empty': 'off',
      'no-dupe-keys': 'off',
      'no-duplicate-imports': 'off',
      'no-useless-catch': 'off',
      'no-constant-binary-expression': 'off',
      'no-unused-private-class-members': 'off',
      'require-atomic-updates': 'off',
      'no-loss-of-precision': 'off',
    },
    ignores: ['node_modules/**', 'test/**', '*.test.mjs', '*.test.js'],
  },
];