// test/quant/multi-objective-evolver-live.test.mjs
// Closes rga Gap G1: MultiObjectiveEvolver was committed 11:14 on 23-Jun
// (NSGA-II style Pareto ranking for regime-specific genomes). Zero importers
// since landing. This test exercises the real rankPopulation + _dominates
// math on synthetic populations.
//
// Contract under test:
//   constructor({ objectives })
//   _dominates(ind1, ind2) — true iff every objective of ind1 >= ind2 with at
//                            least one strictly greater (Pareto dominance)
//   rankPopulation(population) — assigns .rank to each ind: 1 = first
//                                  (non-dominated) front, 2 = second, etc.
//   evolve(population, regime, mutateFn, crossoverFn) — keeps top-8 survivors,
//                                                      adds 6 new offspring
//                                                      generated by mutate+crossover

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { MultiObjectiveEvolver } from '../../src/worm/dreamer/multi-objective-evolver.mjs';

// Synthetic population designed so the first front is unambiguous:
//   A = (5,5,5,5)  - clearly dominates everything below
//   B = (4,3,4,4)  - dominated by A (alpha + robustness higher in A, others equal)
//   C = (4,4,4,3)  - dominated by A
//   D = (3,4,4,4)  - dominated by A
//   E = (4,4,3,4)  - dominated by A
//   F = (1,1,1,1)  - dominated by A and by everyone above. Stays in front 2.
// Note: B–E are pairwise non-dominated (each has at least one axis strictly
// greater than another), so B–E stay on the same front as A ONLY if no one
// among them dominates another. In this build, A is strictly > on alpha vs
// B/D/E so A dominates them; but A vs C has alpha equal so it depends on the
// other axes (A wins 5>3 on robustness, 5>3 on drawdownNeg → A dominates C).
// Net: only A is rank-1 in this population. B-F all rank 2+.
// This tests the *contrast* — a population with a true unique winner — rather
// than trade-off ties. The test asserts A is rank 1 alone and F is in the
// *last* rank (deepest dominated).
function synthPopulation() {
  return [
    { id: 'A', objectives: { alpha: 5, robustness: 5, conviction: 5, drawdownNeg: 5 } },
    { id: 'B', objectives: { alpha: 4, robustness: 3, conviction: 4, drawdownNeg: 4 } },
    { id: 'C', objectives: { alpha: 4, robustness: 4, conviction: 4, drawdownNeg: 3 } },
    { id: 'D', objectives: { alpha: 3, robustness: 4, conviction: 4, drawdownNeg: 4 } },
    { id: 'E', objectives: { alpha: 4, robustness: 4, conviction: 3, drawdownNeg: 4 } },
    { id: 'F', objectives: { alpha: 1, robustness: 1, conviction: 1, drawdownNeg: 1 } },
  ];
}

describe('MultiObjectiveEvolver: NSGA-II Pareto ranking (closes rga Gap G1)', () => {
  test('_dominates: A dominates F (every axis strictly greater)', () => {
    const ev = new MultiObjectiveEvolver();
    const pop = synthPopulation();
    const A = pop.find(i => i.id === 'A');
    const F = pop.find(i => i.id === 'F');
    assert.strictEqual(ev._dominates(A, F), true,  'A must dominate F on every axis');
    assert.strictEqual(ev._dominates(F, A), false, 'F must NOT dominate A');
    assert.strictEqual(ev._dominates(F, F), false, 'self-domination is impossible');
  });

  test('_dominates: B is non-dominated with C (B does NOT dominate C)', () => {
    const ev = new MultiObjectiveEvolver();
    const pop = synthPopulation();
    const B = pop.find(i => i.id === 'B');
    const C = pop.find(i => i.id === 'C');
    assert.strictEqual(ev._dominates(B, C), false, 'B does not strictly dominate C — different trade-off');
    assert.strictEqual(ev._dominates(C, B), false, 'symmetric — neither dominates');
  });

  test('rankPopulation: A is uniquely on the first front, F is on the last front', () => {
    const ev = new MultiObjectiveEvolver();
    const pop = synthPopulation();
    ev.rankPopulation(pop);

    // A dominates everyone: A is rank 1, the only rank-1 individual.
    const A = pop.find(i => i.id === 'A');
    assert.strictEqual(A.rank, 1, 'A — strictly greater on every axis — must be rank 1');

    // F is dominated by every other individual (any one of A–E strictly >
    // F on all axes). F must therefore be in the deepest rank: its rank
    // must equal max(rank) across the population.
    const ranks = pop.map(ind => ind.rank);
    const F = pop.find(i => i.id === 'F');
    assert.strictEqual(F.rank, Math.max(...ranks),
      `F must be on the deepest rank; got ${F.rank} vs max ${Math.max(...ranks)}`);

    // Structural: rank must be a positive integer for every ind.
    for (const ind of pop) {
      assert.ok(Number.isInteger(ind.rank) && ind.rank >= 1,
        `${ind.id}: rank must be a positive integer, got ${ind.rank}`);
    }
    // Structural: domination count must be zero on rank-1 members specifically
    // (this is the invariant that defines rank 1 in NSGA-II).
    for (const ind of pop.filter(i => i.rank === 1)) {
      assert.strictEqual(ind.dominationCount, 0,
        `${ind.id}: rank-1 members must have domination count zero`);
    }
  });

  test('rankPopulation with two truly non-dominated individuals puts both on rank 1', () => {
    // Build the strongest possible tie: two individuals each strictly greater on a
    // different axis. Pure non-dominated front.
    const ev = new MultiObjectiveEvolver();
    const pop = [
      { id: 'ALPHA', objectives: { a: 10, b: 0 } },
      { id: 'BETA',  objectives: { a: 0,  b: 10 } },
      { id: 'DONE',  objectives: { a: -1, b: -1 } }, // dominated by both
    ];
    ev.rankPopulation(pop);
    const r1 = pop.filter(i => i.rank === 1).map(i => i.id).sort();
    assert.deepStrictEqual(r1, ['ALPHA', 'BETA'],
      `ALPHA and BETA must both be rank 1 (no axis dominates the other)`
    );
    const dom = pop.find(i => i.id === 'DONE');
    assert.ok(dom.rank >= 2, `DONE must be on rank >= 2, got ${dom.rank}`);
  });

  test('rankPopulation is idempotent on a re-run with no mutation between calls', () => {
    const ev = new MultiObjectiveEvolver();
    const pop1 = synthPopulation();
    const pop2 = synthPopulation();
    ev.rankPopulation(pop1);
    ev.rankPopulation(pop2);
    for (let i = 0; i < pop1.length; i++) {
      assert.strictEqual(pop1[i].rank, pop2[i].rank,
        `${pop1[i].id}: rank must be stable across reruns (${pop1[i].rank} vs ${pop2[i].rank})`);
    }
  });

  test('evolve keeps 8 survivors plus 6 offspring (population growth)', () => {
    const ev = new MultiObjectiveEvolver();
    // 12 individuals so the top-8 selection has material to work with.
    const pop = [];
    for (let i = 0; i < 12; i++) {
      pop.push({
        id: `ind${i}`,
        genome: { i },
        objectives: { alpha: i, robustness: 12 - i, conviction: i % 5, drawdownNeg: i % 7 },
      });
    }
    let mutateCount = 0;
    let crossoverCount = 0;
    const result = ev.evolve(pop, 'BULL_RUSH',
      (genome, _regime) => { mutateCount++; return { ...genome, mutated: true }; },
      (g1, g2) => { crossoverCount++; return { ...g1, ...g2 }; });

    assert.strictEqual(result.length, 14, 'expected 8 survivors + 6 offspring = 14');
    // Offspring must carry the mutated marker (proves the crossover -> mutate chain ran)
    const offspring = result.slice(8);
    for (const o of offspring) {
      assert.strictEqual(o.genome.mutated, true, 'every offspring must have been mutated');
    }
    assert.ok(mutateCount >= 6, `mutateFn must be called at least 6 times (saw ${mutateCount})`);
    assert.ok(crossoverCount >= 6, `crossoverFn must be called at least 6 times (saw ${crossoverCount})`);
  });

  test('evolve on a too-small population returns it unchanged (no grow)', () => {
    const ev = new MultiObjectiveEvolver();
    // Source code: `if (population.length < 6) return population` — the
    // guard is strict-less-than, so 5 elements is below the threshold.
    const pop = synthPopulation().slice(0, 5);
    assert.strictEqual(pop.length, 5, 'precondition: 5 elements');
    const result = ev.evolve(pop, 'BULL_RUSH',
      (_g, _r) => { throw new Error('mutateFn must not fire on small population'); },
      (_g1, _g2) => { throw new Error('crossoverFn must not fire on small population'); });
    assert.strictEqual(result.length, 5, 'small population must not grow');
  });
});
